channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow==2.22.4
      - azure-ai-ml==1.31.0
      - azure-identity==1.21.0
      - numpy==2.2.6
      - pyarrow==18.1.0
      - scikit-learn==1.7.2
      - pandas==2.3.3
      - joblib==1.4.2
      - matplotlib==3.10.0
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector