channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - azure-ai-ml==1.31.0
      - mlflow==2.22.4
      - azureml-mlflow==1.57.0
      - scikit-learn==1.7.2
      - numpy==2.2.6
      - cloudpickle==3.1.1
      - pandas==2.3.3
