name: taxi-batch-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow==2.16.0
      - azureml-mlflow==1.57.0
      - azure-ai-ml==1.31.0
      - scikit-learn==1.7.2
      - numpy==2.2.6
      - cloudpickle==3.1.1
      - pyarrow==18.1.0
      - scipy==1.15.1
      - pandas==2.3.3
