# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: deploy-model-training-pipeline

parameters:
  - name: skipEnvironmentRegistration
    displayName: Skip Environment Registration
    type: boolean
    default: false
  - name: skipDataRegistration
    displayName: Skip Data Registration
    type: boolean
    default: false

variables:
  - template: ../../../../config-infra-dev.yml

trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: mlops-templates # Template Repo
      name: mlops-templates
      type: git
      ref: ${{ variables.mlops_templates_ref }}

stages:
  - stage: DeployTrainingPipeline
    displayName: Deploy Training Pipeline
    jobs:
      - job: DeployTrainingPipeline
        timeoutInMinutes: 120 # how long to run the job before automatically cancelling
        steps:
          - checkout: self
            path: s/
          - template: templates/aml-cli-v2/setup.yml@mlops-templates
            parameters:
              azure_service_connection: $(ado_service_connection_aml_ws)
              resource_group: $(resource_group)
              workspace_name: $(aml_workspace)
              working_directory: $(System.DefaultWorkingDirectory)
          - ${{ if ne(parameters.skipEnvironmentRegistration, true) }}:
            - template: templates/aml-cli-v2/register-environment.yml@mlops-templates
              parameters:
                azure_service_connection: $(ado_service_connection_aml_ws)
                resource_group: $(resource_group)
                workspace_name: $(aml_workspace)
                working_directory: $(System.DefaultWorkingDirectory)
                environment_name: $(training_environment_name)
                environment_file: classical/aml-cli-v2/mlops/azureml/train/train-env.yml
          - ${{ if ne(variables.enable_aml_computecluster, 'true') }}:
            - template: templates/aml-cli-v2/create-compute.yml@mlops-templates
              parameters:
                azure_service_connection: $(ado_service_connection_aml_ws)
                resource_group: $(resource_group)
                workspace_name: $(aml_workspace)
                cluster_name: $(training_compute_name)
                size: $(aml_compute_sku)
                min_instances: 0
                max_instances: 4
                cluster_tier: low_priority
          - ${{ if ne(parameters.skipDataRegistration, true) }}:
            - template: templates/aml-cli-v2/register-data.yml@mlops-templates
              parameters:
                azure_service_connection: $(ado_service_connection_aml_ws)
                resource_group: $(resource_group)
                workspace_name: $(aml_workspace)
                working_directory: $(System.DefaultWorkingDirectory)
                data_type: uri_file
                data_name: $(training_data_name)
                data_file: classical/aml-cli-v2/mlops/azureml/train/data.yml
          - template: templates/aml-cli-v2/run-pipeline.yml@mlops-templates
            parameters:
              azure_service_connection: $(ado_service_connection_aml_ws)
              resource_group: $(resource_group)
              workspace_name: $(aml_workspace)
              working_directory: $(System.DefaultWorkingDirectory)
              pipeline_file: classical/aml-cli-v2/mlops/azureml/train/pipeline.yml
              experiment_name: $(environment)_taxi_fare_train_$(Build.SourceBranchName)
              display_name: $(environment)_taxi_fare_run_$(Build.BuildID)
              enable_monitoring: $(enable_monitoring)
