# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: deploy-batch-endpoint-pipeline

variables:
  - template: ../../../../config-infra-dev.yml
  - name: endpoint_name
    value: $(batch_endpoint_name)
  - name: endpoint_type
    value: batch

trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: mlops-templates # Template Repo
      name: mlops-templates
      type: git
      ref: ${{ variables.mlops_templates_ref }}

stages:
  - stage: CreateBatchEndpoint
    displayName: Create/Update Batch Endpoint
    jobs:
      - job: DeployBatchEndpoint
        steps:
          - checkout: self
            path: s/
          - template: templates/aml-cli-v2/setup.yml@mlops-templates
            parameters:
              azure_service_connection: $(ado_service_connection_aml_ws)
              resource_group: $(resource_group)
              workspace_name: $(aml_workspace)
              working_directory: $(System.DefaultWorkingDirectory)
          - template: templates/aml-cli-v2/create-compute.yml@mlops-templates
            parameters:
              azure_service_connection: $(ado_service_connection_aml_ws)
              resource_group: $(resource_group)
              workspace_name: $(aml_workspace)
              cluster_name: $(batch_compute_name) # name must match cluster name in deployment file below
              size: STANDARD_D4S_V5
              min_instances: 0
              max_instances: 5
              cluster_tier: dedicated
          - template: templates/aml-cli-v2/create-endpoint.yml@mlops-templates
            parameters:
              azure_service_connection: $(ado_service_connection_aml_ws)
              resource_group: $(resource_group)
              workspace_name: $(aml_workspace)
              endpoint_type: batch
              endpoint_name: $(endpoint_name)
              endpoint_file: classical/aml-cli-v2/mlops/azureml/deploy/batch/batch-endpoint.yml
          - template: templates/aml-cli-v2/create-deployment.yml@mlops-templates
            parameters:
              azure_service_connection: $(ado_service_connection_aml_ws)
              resource_group: $(resource_group)
              workspace_name: $(aml_workspace)
              endpoint_type: batch
              endpoint_name: $(endpoint_name)
              deployment_name: $(batch_deployment_name)
              deployment_file: classical/aml-cli-v2/mlops/azureml/deploy/batch/batch-deployment.yml
          - template: templates/aml-cli-v2/test-deployment.yml@mlops-templates
            parameters:
              azure_service_connection: $(ado_service_connection_aml_ws)
              resource_group: $(resource_group)
              workspace_name: $(aml_workspace)
              endpoint_type: batch
              endpoint_name: $(endpoint_name)
              working_directory: $(System.DefaultWorkingDirectory)
              deployment_name: $(batch_deployment_name)
              sample_request: classical/aml-cli-v2/data/taxi-batch.csv
              request_type: uri_file #either uri_folder or uri_file
