#!/usr/bin/env bash

SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID:?AZURE_SUBSCRIPTION_ID is required}
LOCATION=${LOCATION:-eastus2}
HUB_RESOURCE_GROUP=${ARC_HUB_RESOURCE_GROUP:-rg-mlops-hub-dev-eus2-001}
HUB_VNET=${ARC_HUB_VNET:-vnet-mlops-hub-dev-eus2-001}
RUNNER_SUBNET_NAME=${ARC_RUNNER_SUBNET_NAME:-snet-github-runners}
RUNNER_SUBNET_PREFIX=${ARC_RUNNER_SUBNET_PREFIX:-10.240.2.0/24}
NODE_SKU=${ARC_NODE_SKU:-Standard_D2ads_v6}
SYSTEM_NODE_COUNT=${ARC_SYSTEM_NODE_COUNT:-2}
