# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: tf-ado-deploy-infra

variables:
  - template: ../../../config-infra-dev.yml

trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: mlops-templates
      name: mlops-templates
      type: git
      ref: ${{ variables.mlops_templates_ref }}

stages:
  - stage: BootstrapTerraformState
    displayName: Bootstrap Terraform state
    jobs:
      - job: BootstrapTerraformState
        displayName: Bootstrap Terraform state
        steps:
          - checkout: none
          - template: templates/infra/terraform-state-bootstrap.yml@mlops-templates
            parameters:
              azureServiceConnection: $(ado_service_connection_rg)
              cicdPrincipalObjectId: $(cicd_principal_object_id)
              location: $(terraform_st_location)
              backendResourceGroup: $(terraform_st_resource_group)
              backendStorageAccount: $(terraform_st_storage_account)
              backendContainer: $(terraform_st_container_name)

  - stage: DeployAzureMachineLearning
    displayName: Deploy Azure Machine Learning
    dependsOn: BootstrapTerraformState
    jobs:
      - job: DeployAzureMachineLearning
        displayName: Deploy Terraform
        steps:
          - checkout: self
            path: s/
          - template: templates/infra/terraform-deploy.yml@mlops-templates
            parameters:
              azureServiceConnection: $(ado_service_connection_rg)
              terraformVersion: $(terraform_version)
              workingDirectory: $(System.DefaultWorkingDirectory)/$(terraform_workingdir)
              backendResourceGroup: $(terraform_st_resource_group)
              backendStorageAccount: $(terraform_st_storage_account)
              backendContainer: $(terraform_st_container_name)
              backendKey: $(terraform_st_key)
              location: $(location)
              prefix: $(namespace)
              postfix: $(postfix)
              projectNumber: $(project_number)
              environment: $(environment)
              enableAmlComputeCluster: ${{ eq(variables.enable_aml_computecluster, 'true') }}
              amlComputeSku: $(aml_compute_sku)
              enableMonitoring: ${{ eq(variables.enable_monitoring, 'true') }}
              cicdPrincipalObjectId: $(cicd_principal_object_id)
              enablePrivateEndpoints: ${{ eq(variables.enable_private_endpoints, 'true') }}
              vnetAddressSpace: $(vnet_address_space)
              trainingSubnetAddressPrefix: $(training_subnet_address_prefix)
              endpointsSubnetAddressPrefix: $(endpoints_subnet_address_prefix)
              planFile: tfplan
              apply: true
